version: "3.8"
services:
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
  api:
    build: ./api
    container_name: api_c
    ports:
      - '5000:5000'
    stdin_open: true
    tty: true